version: "3.3"

services:
  mercadolibreapp:
    ports:
      - 3000:3000
    build:
      context: Frontend
      dockerfile: Dockerfile
    depends_on:
      - mercadolibreapi

  mercadolibreapi:
    ports:
      - 3001:8080
    build:
      context: Backend
      dockerfile: Dockerfile
